/**
 * Created by chungch on 6/29/2017.
 */
const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
const CREATE_COURSE = 'CREATE_COURSE';
const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS';
const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
const BEGIN_AJAX_CALL ='BEGIN_AJAX_CALL';
const LOAD_MATCHES_SUCCESS = 'LOAD_MATCHES_SUCCESS';
const CREATE_MATCH ='CREATE_MATCH';
const UPDATE_MATCH_SUCCESS ='UPDATE_MATCH_SUCCESS';
const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';

export {CREATE_COURSE, LOAD_MATCHES_SUCCESS,
     CREATE_COURSE_SUCCESS, LOAD_COURSE_SUCCESS, LOAD_AUTHORS_SUCCESS,
     UPDATE_COURSE_SUCCESS,BEGIN_AJAX_CALL,
     CREATE_MATCH,UPDATE_MATCH_SUCCESS,CREATE_MATCH_SUCCESS}
