/**
 * Created by chungch on 6/29/2017.
 */
const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
const CREATE_COURSE = 'CREATE_COURSE';
const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS';
const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
const BEGIN_AJAX_CALL ='BEGIN_AJAX_CALL';

export {CREATE_COURSE, CREATE_COURSE_SUCCESS, LOAD_COURSE_SUCCESS, LOAD_AUTHORS_SUCCESS,UPDATE_COURSE_SUCCESS,BEGIN_AJAX_CALL}
