/**
 * Created by chungch on 6/29/2017.
 */
const CREATE_COURSE_SUCESSS = 'CREATE_COURSE_SUCESSS';
const LOAD_COURSE_SUCCESS = "LOAD_COURSE_SUCCESS";
const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
const UPDATE_COURSE_SUCESSS = 'UPDATE_COURSE_SUCESSS';

export {CREATE_COURSE_SUCESSS, LOAD_COURSE_SUCCESS, LOAD_AUTHORS_SUCCESS,UPDATE_COURSE_SUCESSS}
